#!/bin/sh
##############################################################################
# Run parallel Navier--Stokes solver regression checks.
# NB: you may need to edit the string MPIRUN to run a 2-process MPI job.
#
# $Id: testregress_mp,v 8.1 2015/04/20 11:14:18 hmb Exp $

case $# in
0) echo "usage: testregress_mp new_code_version"; exit 0
esac

EXEC=$1
CODE=$2
TEST=$3
MESHDIR=../mesh
PATH=.:$PATH

if test ! -f $TEST
then
  cp $MESHDIR/$TEST .
fi
if test -f $TEST.num
then
  rm -f $TEST.num
fi
../build/enumerate -O3 $TEST > $TEST.num 2> /dev/null
../build/compare $TEST > $TEST.rst
$EXEC $CODE -chk $TEST > /dev/null 2>&1
../build/compare -n $TEST $TEST.fld > /dev/null 2> $TEST.new
cmp -s $TEST.new ../regress/MPI/$TEST.ok
case $? in
0) echo passed: $TEST ;;
1) echo failed: $TEST ;;
esac
rm $TEST*
