#!/bin/csh
##############################################################################
# An example script that automates NP-convergence testing.
#
# $Id$
##############################################################################

if ($#argv < 1) then 
    echo "usage: testconvg session"
    exit 0
endif

set SESSION = $1

foreach i (3 4 5 6 7 8 9 10 11 12)
    sed "s/N_POLY.*/N_POLY=$i/" < $SESSION > _conv
    echo NP=$i
    enumerate -O3 _conv > _conv.num
    compare _conv > _conv.rst
    dns _conv > /dev/null
    compare _conv _conv.fld > errors.fld
end

rm -f _conv*

