#!/bin/bash
##############################################################################
# Run parallel Navier--Stokes solver regression checks.
# NB: you may need to edit the string MPIRUN to run a 2-process MPI job.
#
# NB: Since the deletion of dealiasing in Fourier direction, this
# script is basically redundant since the serial and parallel codes
# should get almost exactly the same outcomes.
#
# $Id: testregress_mp,v 9.1 2019/05/30 06:36:11 hmb Exp $

case $# in
0) echo "usage: testregress_mp new_code_version"; exit 0
esac

CODE=$1
MESHDIR=../mesh
MPIRUN="mpirun -np 2"
PATH=.:$PATH

for i in taylor3 taylor4 taylor5 kovas2 kovas3 kovas4 kovas5
do
  if test ! -f $i
  then
    cp $MESHDIR/$i .
  fi
  if test -f $i.num
  then
    rm -f $i.num
  fi
  enumerate -O3 $i > $i.num 2> /dev/null
  compare $i > $i.rst
  $MPIRUN $CODE -chk $i > /dev/null 2>&1
  compare -n $i $i.fld > /dev/null 2> $i.new
  cmp -s $i.new ../regress/MPI/$i.ok
  if [ $? -ne 0 ]
  then
      echo failed: $i
  else
      echo passed: $i      
  fi
  rm $i*
done
