#!/bin/csh
##############################################################################
# An example script that automates NP-convergence testing.
#
# $Id: testconvg,v 9.2 2019/06/22 08:43:26 hmb Exp $
##############################################################################

if ($#argv < 1) then 
    echo "usage: testconvg session"
    exit 0
endif

set SESSION = $1

#foreach i (3 4 5 6 7 8 9 10 11 12 13 14)
#    sed "s/N_P.*/N_P=$i/" < $SESSION > _conv
#    echo NP=$i
#    compare _conv > _conv.rst
#    enumerate -O3 _conv > _conv.num
#    dns _conv > /dev/null
#    compare _conv _conv.fld > errors.fld
#end

#rm -f _conv*

foreach i (4 6 8 10 12 16 20 24 30 32 36 40 48 50) 
    sed "s/N_Z.*/N_Z=$i/" < $SESSION > _conv
    echo NZ=$i
    compare _conv > _conv.rst
    enumerate -O3 _conv > _conv.num
    dns _conv > /dev/null
    compare _conv _conv.fld > errors.fld
end

rm -f _conv*

