#!/bin/bash

export CVSROOT=hmb@mec-discus.eng.monash.edu.au:/Users/hmb/Repository
export CVS_RSH=ssh
export HTTP_PROXY=http://bburn:hb51hmb58@proxy.monash.edu.au:8080
export  FTP_PROXY=http://bburn:hb51hmb58@proxy.monash.edu.au:8080

cvs export -Dnow semtex
tar czvf semtex.tgz semtex
cp /Users/hmb/develop/semtex-ug/userguide.pdf semtex-user.pdf
cp /Users/hmb/develop/webpage/semtex-web.html semtex.html

curl -T "{semtex.tgz,semtex-user.pdf,semtex.html}" ftp://hugh.blackburn:hot4Texta@users.bigpond.net.au

rm -rf semtex semtex.tgz semtex-user.pdf semtex.html
