#!/bin/bash
# $Id: testrun,v 1.6 2009/03/31 09:26:19 hmb Exp $
###############################################################################

enumerate -O3 vb2_bse > vb2_bse.num
dns vb2_bse > /dev/null
mv vb2_bse.fld vb2.bse

enumerate -O3 vb2 > vb2.num
../../dog -k 13 -m 40 -n 1 vb2 > /dev/null
