#!/bin/bash
#
# splice: join 3-component velocity data in field file file1 to scalar
# data in file2 and write the outcome in ASCII to standard output (you
# will need to put the outcome through convert to get a binary restart
# file).
#

# WARNING: this is a hack, based on xfield. Assume that we will (be
# able to) take u v w p from file1 and c from file2, where it comes
# before the pressure (i.e. the ordering is u v w c p) in that
# file. And of course that the two field files conform, etc. If some
# of these things are untrue there will be trouble.

#
# Usage: splice file1 file2
#
# $Id $
##############################################################################

if [ $# -ne 2 ]
then
  echo 'usage: splice file1 file2' 1>&2; exit 2
else
  file1=$1
  file2=$2
fi

# -- Generate header from file1

convert -a $file1 | head > hdr.asc
ed -s hdr.asc << XXXoooXXX
9d
8a
uvwpc                     Fields written
.
w
q
XXXoooXXX

cat hdr.asc
rm hdr.asc

# -- Extract u, v, w, p from file1 (first 4 variables)

convert -a $file1 | chop -s 11 | slit -c 1 > .f1
convert -a $file1 | chop -s 11 | slit -c 2 > .f2
convert -a $file1 | chop -s 11 | slit -c 3 > .f3
convert -a $file1 | chop -s 11 | slit -c 4 > .f4

# -- Extract c from file2 (4th of 5 variables)

convert -a $file2 | chop -s 11 | slit -c 4 > .f5

pr -m -t -s" " .f1 .f2 .f3 .f4 .f5

#rm .f1 .f2 .f3 .f4 .f5

exit 0

