#!/bin/csh
#
set cc     = "cc"
set cflags = "-DCRAY"
set optcc  = ""
set fc     = "cf77"
set fflags = "-DCRAY"
set optfc  = "-dp"
set opt    = ""
set ranlib = ":"
set ar     = "ar"
set aflags = "rlc"
set ld     = "cc"
set lflags = ""
set flags  = ""
set blas   = "-lsci"
set lapack = "-lsci"
set comm   = ""
set system = "-lm"
#
foreach arg ($argv) 
    switch ($arg) 
	case -debug:
	    set opt = "-g"
	    breaksw
	case -blas=*:
	    set blas = `echo $arg | awk '{FS="="; print $2}'`
	    breaksw
	case -lapack=*:
	    set lapack = `echo $arg | awk '{FS="="; print $2}'`
	    breaksw
	default:
	    breaksw
    endsw
end
#
cat <<EOF
#
# default settings for CRAY (XMP, YMP, C90, J90, T90)
#
ARCH     = CRAY
#
# compilers and switches
#
CC	 = $cc
CFLAGS   = $opt $optcc $cflags
FC	 = $fc
FFLAGS   = $opt $optfc $fflags
AR       = $ar
ARFLAGS  = $aflags
RANLIB   = $ranlib
LD       = $ld
LDFLAGS  = $lflags
#
# misc flags
#
FLAGS    = $flags
#
# libraries
#
SPECLIB  = -lspec
MORTAR   = -lmortar
VECLIB   = -lvec
LAPACK   = $lapack
BLAS     = $blas
COMM     = $comm
SYSTEM   = $system
EOF
exit 0
