#!/bin/bash
#
# change field name 'c' to field name 'w'
# usage c2w Re file.fld
#
# This converts the scalar in the roll-streak solution to streak
# velocity w and sets the other velocity components (and pressure) to zero.
##############################################################################

if [ $# -ne 1 ]
then
    echo "usage: c2w field"
    exit 1
fi

convert -a $1 | head | sed 's/uvcp/uvwp/' 
convert $1 | chop -s 11 | awk '{       \
   printf "0 0 %17.8e 0\n", $3 }'

