#!/bin/bash

# We test dual by comparing it to results obtained using dns with a
# single Fourier mode.  As dns is dealiased, the results should be the
# same.
# 
# $Id$

SEM=../../semtex

# TESTCASES

# Taylor3: a 3D Cartesian flow that lies in the x--y plane (so can be
# solved in 2D.

# Tc1: a 3D cylindrical axisymmetric flow, with only a swirl component
# (likewise can be solved in 2D).

# Taylor4: a 3D Cartesian flow in the x--z plane.

for i in taylor3 tc1 taylor4
do

  echo ""

  sed "s/N_Z.*=.*/N_Z=4/" < $SEM/mesh/$i > tmp
  mv tmp $i

  compare $i > $i.rst
  dns $i > /dev/null
  cp $i.fld $i.dns.fld

  sed "s/N_Z.*=.*/N_Z=3/" < $i > tmp
  mv tmp $i
  dual2sem -i $i.rst > tmp
  mv tmp $i.rst
  ../dual $i > /dev/null
  dual2sem $i.fld > $i.dual.fld

  sed "s/N_Z.*=.*/N_Z=4/" < $SEM/mesh/$i > tmp
  mv tmp $i
  rstress $i.dns.fld $i.dual.fld > diff.fld
  convert diff.fld | head -23
 
  rm $i $i.rst $i.num $i.dns.fld $i.dual.fld $i.fld $i.flx $i.mdl
done
