# Make a PDF of the semtex user guide.
#
# $Id: Makefile,v 9.1 2019/05/30 06:36:03 hmb Exp $
###############################################################################

default:
	pdflatex userguide
	bibtex userguide
	pdflatex userguide
	pdflatex userguide
