#!/bin/bash
# $Id: testrun,v 1.5 2008/05/19 13:05:22 hmb Exp $
##############################################################################

enumerate -O3 chan3 > chan3.num
../../dog -k 16 -n 1 -m 500 -t 1e-6 chan3 > /dev/null
