/*===========================================================================
 * RCS Information:
 * ----------------
 * $Author$
 * $Date$
 * $Source$
 * $Revision$
 *===========================================================================*/

/*===========================================================================*/
/* From a restart-file generated by iso, compute the maximum divergence of   */
/* the velocity-field.  Diagnostic; print result on stdout.                  */
/* Usage: div_chk file                                                       */
/*===========================================================================*/

#include "globals.h"

#define MAX(x, y)    ((x) > (y)) ? (x) : (y)


main(int argc, char *argv[])
{
  complex_vector_field U, D;
  component_handle     headU, headD;
  ivector              Dim;
  cvector              Wtab;
  header               Run_info;
  int                  i, c, Npts;
  float                div, Max=0.0;
  FILE                 *fp;

  if (argc != 2) {
    fprintf(stderr, "div_chk: arg count\n");
    fprintf(stderr, "Usage: div_chk file\n");
    exit(1);
  }

  /*-------------------------------------------------------------------------*/
  /* Open restart file, allocate storage, read velocity Fourier components.  */
  /*-------------------------------------------------------------------------*/
  fp = efopen(argv[1], "r");
      
  if (fread((char *)&Run_info, 1, sizeof(header), fp) != sizeof(header))
    error("Can't get header from restart file");
  if (Run_info.Magic != MAGIC)
    error("Nominated file is not a restart file");
  
  Dim = ivect(1, 3);
  Dim[1] = (Dim[2] = Run_info.N_Grid);
  Dim[3] =  Dim[1] / 2;
  Npts = Dim[1]*Dim[2]*Dim[3];

  headU = cfield(Dim, &U);
  headD = cfield(Dim, &D);

  read_components(fp, U, Npts);
    
  (void) fclose(fp);

  /*-------------------------------------------------------------------------*/
  /* Do dUi/dXi unsummed in Fourier space.                                   */
  /*-------------------------------------------------------------------------*/
  deriv(U, 1, D[1], 1, Dim);
  deriv(U, 2, D[2], 2, Dim);
  deriv(U, 3, D[3], 3, Dim);

  /*-------------------------------------------------------------------------*/
  /* Transform to physical space.                                            */
  /*-------------------------------------------------------------------------*/
  Wtab = cvect(0, Dim[3]-1); 
  preFFT(Dim[3], Wtab);

  rc3DFT(D[1], Dim, Wtab, INVERSE);
  rc3DFT(D[2], Dim, Wtab, INVERSE);
  rc3DFT(D[3], Dim, Wtab, INVERSE);

  /*-------------------------------------------------------------------------*/
  /* Find maximum divergence.                                                */
  /*-------------------------------------------------------------------------*/
  for (i=0; i<2*Npts; i++) {
    div = headD[1][i] + headD[2][i] + headD[3][i];
    Max = MAX(div, Max);
  }

  printf("%.3e\n", Max);
  
  exit(0);
}
