#!/bin/csh
##############################################################################
# Run Fourier--Galerkin Navier--Stokes solver on test cases.
# $Id$

echo "Building application, please wait..."
  gmake veryclean
  gmake

echo "******************************************************"
echo "* Fourier spectral Navier--Stokes solver test suite. *"
echo "******************************************************"

# Note the 2D Taylor flow can be integrated exactly by the integrating
# factor method.  So any order timestepping should work exactly.  Here
# we try 1st, 2nd & 3rd order.

echo ""
makeIC3 -n 16 -o testsession.rst -p 0 > /dev/null
time iso -d 0.025 -n 50 -k 0.01 -o 1 testsession
taylor2D_chk -p 0 testsession.fld > /dev/null

echo ""
makeIC3 -n 16 -o testsession.rst -p 1 > /dev/null
time iso -d 0.025 -n 50 -k 0.01 -o 2 testsession
taylor2D_chk -p 1 testsession.fld > /dev/null

echo ""
makeIC3 -n 16 -o testsession.rst -p 2 > /dev/null
time iso -d 0.025 -n 50 -k 0.01 -o 3 testsession
taylor2D_chk -p 2 testsession.fld > /dev/null

# The inviscid Taylor--Green vortex.  Either leapfrog or AB3 should
# work fine.  And for the short time run here, any timestepping method
# should work OK.

echo ""
rm -f iso
gmake clean
gmake iso TG=1 INVISCID=1
makeIC2 -n 32 -o testsession.rst > /dev/null
time iso -d 0.01 -n 50 -o 2 testsession

echo ""
echo "cleaning up..."
rm -f iso
gmake clean
gmake
