#!/bin/bash
#
# Print a sequence of numbers from "start" to "end" in steps "inc",
# using awk.  This functionality is usually present with the shell
# utility seq, but that does not always exist.
#
# Usage: index <start> <end> <inc>
#
# $Id: index,v 9.1 2019/05/30 06:36:12 hmb Exp $

echo $1 $2 $3 | awk '
  {
	start = $1 ;
	end   = $2 ;
	inc   = $3 
  }
  END {
	 for (i = start; i <= end; i += inc)
	 print i
  } '
