#!/bin/csh
#
# Usage: resubmit session time
#
# Returns 1 if the final time in session.rst exceeds time (i.e. no
# resubmit), else 0.  This can be used in many queuing systems as part
# of a termination test.
#
# If no awk, or gawk, try nawk.
#
# $Id: resubmit,v 9.1 2019/05/30 06:36:12 hmb Exp $

head $1.rst | grep Time | grep -v step | \
	awk '{t = $1} \
	END {if (t >= '$2') exit 1; else exit 0 }'

