#!/bin/csh
##############################################################################
# Run aeroelastic Navier--Stokes solver on test files.
#
# Note that when BCs are applied, this code can only be run with the
# z direction as the Fourier direction.
#
# $Id$

if (!(-e aero)) then
	echo "Building application, please wait..."
	if { gmake } then
	    gmake clean
	    echo "Done."
	else
	    echo "Unable to compile."
	    exit 1
	endif
	echo ""
endif

echo "\t******************************************************"
echo "\t* Spectral element Navier--Stokes solver test suite. *"
echo "\t*             ### Aeroelastic solver ###             *"
echo "\t*                                                    *"
echo "\t* (NB: pressure error norms are usually irrelevant.) *"
echo "\t******************************************************"

rm -f *.num

if (!(-e kovas1))  cp ../semtex-5.2/mesh/kovas1  .
if (!(-e kovas2))  cp ../semtex-5.2/mesh/kovas2  .
if (!(-e kovas3))  cp ../semtex-5.2/mesh/kovas3  .
if (!(-e taylor2)) cp ../semtex-5.2/mesh/taylor2 .
if (!(-e taylor3)) cp ../semtex-5.2/mesh/taylor3 .
if (!(-e taylor4)) cp ../semtex-5.2/mesh/taylor4 .
if (!(-e taylor5)) cp ../semtex-5.2/mesh/taylor5 .
if (!(-e box1))    cp ../semtex-5.2/mesh/box1*   .
if (!(-e box2))    cp ../semtex-5.2/mesh/box2*   .

echo "\n\t*** 2D TESTS ***"

echo ""
echo "-- 2D TAYLOR FLOW, PERIODIC (i.e. NO) BOUNDARIES"
compare taylor2 > taylor2.rst
aero -chk taylor2 > /dev/null
compare taylor2 taylor2.fld > /dev/null
rm taylor2*

echo ""
echo "-- 2D KOVASZNAY FLOW, DIRICHLET BCS"
aero -chk kovas1 > /dev/null
compare kovas1 kovas1.fld > /dev/null
rm kovas1*

echo "\n\t*** AEROELASTIC TESTS ***"

echo ""
echo "-- 2D FLOW IN ACCELERATING BOX, PERIODIC BOUNDARIES"
echo "NB: can fail on a vector machine"
aero box1 > /dev/null
compare box1 box1.fld > /dev/null
rm box1*

echo ""
echo "-- 2D FLOW IN ACCELERATING BOX, DIRICHLET BOUNDARIES"
aero box2 > /dev/null
compare box2 box2.fld > /dev/null
rm box2*

echo "\n\t*** 3D TESTS ***"

echo ""
echo "-- 2D TAYLOR FLOW, 3D SOLUTION IN X--Y PLANE"
compare taylor3 > taylor3.rst
aero -chk taylor3 > /dev/null
compare taylor3 taylor3.fld > /dev/null
rm taylor3*

echo ""
echo "-- 2D TAYLOR FLOW, 3D SOLUTION IN X--Z PLANE"
compare taylor4 > taylor4.rst
aero -chk taylor4 > /dev/null
compare taylor4 taylor4.fld > /dev/null
rm taylor4*

echo ""
echo "-- 2D TAYLOR FLOW, 3D SOLUTION IN Y--Z PLANE"
compare taylor5 > taylor5.rst
aero -chk taylor5 > /dev/null
compare taylor5 taylor5.fld > /dev/null
rm taylor5*

echo ""
echo "-- 3D KOVASZNAY FLOW, X--Y PLANE, DIRICHLET BCS"
aero -chk kovas2 > /dev/null
compare kovas2 kovas2.fld > /dev/null
rm kovas2*

echo ""
echo "-- 3D KOVASZNAY FLOW, X--Y PLANE, SEMI-PERIODIC BOUNDARIES"
aero -chk kovas3 > /dev/null
compare kovas3 kovas3.fld > /dev/null
rm kovas3*
