#!/bin/csh
##############################################################################
# Run aeroelastic Navier--Stokes solver on test files.
#
# Note that when BCs are applied, this code can only be run with the
# z direction as the Fourier direction.
#
# $Id$

echo "******************************************************"
echo "* Spectral element Navier--Stokes solver test suite. *"
echo "*             ### Aeroelastic solver ###             *"
echo "*                                                    *"
echo "* (NB: pressure error norms are usually irrelevant.) *"
echo "******************************************************"

set CODE=aero
set MESHDIR=../semtex/mesh

if (!(-e $CODE)) then
	echo "Building application, please wait..."
	if { gmake } then
	    gmake clean
	    echo "Done."
	else
	    echo "Unable to compile."
	    exit 1
	endif
	echo ""
endif

rm -f *.num

if (!(-e kovas1))  cp $MESHDIR/kovas1  .
if (!(-e kovas2))  cp $MESHDIR/kovas2  .
if (!(-e kovas3))  cp $MESHDIR/kovas3  .
if (!(-e taylor2)) cp $MESHDIR/taylor2 .
if (!(-e taylor3)) cp $MESHDIR/taylor3 .
if (!(-e taylor4)) cp $MESHDIR/taylor4 .
if (!(-e taylor5)) cp $MESHDIR/taylor5 .
if (!(-e box1))    cp $MESHDIR/box1*   .
if (!(-e box2))    cp $MESHDIR/box2*   .

echo "\n\t*** 2D TESTS ***"

echo ""
echo "-- 2D TAYLOR FLOW, PERIODIC (i.e. NO) BOUNDARIES"
compare taylor2 > taylor2.rst
$CODE -chk taylor2 > /dev/null
compare taylor2 taylor2.fld > /dev/null
rm taylor2*

echo ""
echo "-- 2D KOVASZNAY FLOW, DIRICHLET BCS"
$CODE -chk kovas1 > /dev/null
compare kovas1 kovas1.fld > /dev/null
rm kovas1*

echo "\n\t*** AEROELASTIC TESTS ***"

echo ""
echo "-- 2D FLOW IN ACCELERATING BOX, PERIODIC BOUNDARIES"
echo "NB: can fail on a vector machine"
$CODE box1 > /dev/null
compare box1 box1.fld > /dev/null
rm box1*

echo ""
echo "-- 2D FLOW IN ACCELERATING BOX, DIRICHLET BOUNDARIES"
$CODE box2 > /dev/null
compare box2 box2.fld > /dev/null
rm box2*

echo "\n\t*** 3D TESTS ***"

echo ""
echo "-- 2D TAYLOR FLOW, 3D SOLUTION IN X--Y PLANE"
compare taylor3 > taylor3.rst
$CODE -chk taylor3 > /dev/null
compare taylor3 taylor3.fld > /dev/null
rm taylor3*

echo ""
echo "-- 2D TAYLOR FLOW, 3D SOLUTION IN X--Z PLANE"
compare taylor4 > taylor4.rst
$CODE -chk taylor4 > /dev/null
compare taylor4 taylor4.fld > /dev/null
rm taylor4*

echo ""
echo "-- 2D TAYLOR FLOW, 3D SOLUTION IN Y--Z PLANE"
compare taylor5 > taylor5.rst
$CODE -chk taylor5 > /dev/null
compare taylor5 taylor5.fld > /dev/null
rm taylor5*

echo ""
echo "-- 3D KOVASZNAY FLOW, X--Y PLANE, DIRICHLET BCS"
compare kovas2 > kovas2.rst
$CODE -chk kovas2 > /dev/null
compare kovas2 kovas2.fld > /dev/null
rm kovas2*

echo ""
echo "-- 3D KOVASZNAY FLOW, X--Y PLANE, SEMI-PERIODIC BOUNDARIES"
compare kovas3 > kovas3.rst
$CODE -chk kovas3 > /dev/null
compare kovas3 kovas3.fld > /dev/null
rm kovas3*
