##############################################################################
# Assemble bibliography.
##############################################################################

bib:
	cat jrnl.bib pubs.bib book.bib turb.bib wakes.bib num.bib	\
	mesh.bib tmodel.bib part.bib disper.bib wear.bib bl.bib		\
	twoph.bib nonnew.bib free.bib report.bib electro.bib 		\
	topo.bib bubbly.bib nmr.bib mix.bib visco.bib nldyn.bib 	\
	stab.bib natcon.bib acoust.bib actuator.bib les.bib 		\
	sem.bib machine.bib swirl.bib iwave.bib chroma.bib              \
	mechanics.bib viv.bib flap.bib rotate.bib aero.bib spray.bib    \
	compress.bib sphere.bib equip.bib combust.bib expttech.bib      \
	bio.bib ring.bib fuelcell.bib mhd.bib tc.bib > hmb.bib;         \
#	cd ..; if test ! -f hmb.bib ; then ln -s bibsrc/hmb.bib . ; fi

clean:
	rm -f *~

