#!/bin/csh
##############################################################################
# Run Navier--Stokes solver on test files.
# $Id$

if (!(-e les)) then
	echo "Building application, please wait..."
	if { gmake DEBUG=1 } then
	    gmake clean
	    echo "Done."
	else
	    echo "Unable to compile."
	    exit 1
	endif
	echo ""
endif

echo "\t******************************************************"
echo "\t* Spectral element Navier--Stokes solver test suite. *"
echo "\t*   This is for DNS version of LES solver, must be   *"
echo "\t*              compiled with DEBUG=1.                *"
echo "\t*                                                    *"
echo "\t* (NB: pressure error norms are usually irrelevant.) *"
echo "\t******************************************************"

rm -f *.num

# -- Cartesian geometries.

if (!(-e kovas1))  cp ../mesh/kovas1  .
if (!(-e kovas2))  cp ../mesh/kovas2  .
if (!(-e kovas3))  cp ../mesh/kovas3  .
if (!(-e kovas4))  cp ../mesh/kovas4  .
if (!(-e kovas5))  cp ../mesh/kovas5  .
if (!(-e taylor2)) cp ../mesh/taylor2 .
if (!(-e taylor3)) cp ../mesh/taylor3 .
if (!(-e taylor4)) cp ../mesh/taylor4 .
if (!(-e taylor5)) cp ../mesh/taylor5 .

# -- Cylindrical geometries.

if (!(-e tube1))  cp ../mesh/tube1  .
if (!(-e tube2))  cp ../mesh/tube2  .
if (!(-e tube3))  cp ../mesh/tube3  .
if (!(-e sbr))    cp ../mesh/sbr  .
if (!(-e tc1))    cp ../mesh/tc1  .

echo ""
echo ""
echo "-- CARTESIAN GEOMETRY --"

echo "\n\t*** 2D TESTS ***"

echo ""
echo "-- 2D TAYLOR FLOW, PERIODIC (i.e. NO) BOUNDARIES"
compare taylor2 > taylor2.rst
les -chk taylor2 > /dev/null
compare taylor2 taylor2.fld > /dev/null
rm taylor2*

echo ""
echo "-- 2D KOVASZNAY FLOW, DIRICHLET BCS"
les -chk kovas1 > /dev/null
compare kovas1 kovas1.fld > /dev/null
rm kovas1*

echo "\n\t*** 3D TESTS ***"

echo ""
echo "-- 2D TAYLOR FLOW, 3D SOLUTION IN X--Y PLANE"
compare taylor3 > taylor3.rst
les -chk taylor3 > /dev/null
compare taylor3 taylor3.fld > /dev/null
rm taylor3*

echo ""
echo "-- 2D TAYLOR FLOW, 3D SOLUTION IN X--Z PLANE"
compare taylor4 > taylor4.rst
les -chk taylor4 > /dev/null
compare taylor4 taylor4.fld > /dev/null
rm taylor4*

echo ""
echo "-- 2D TAYLOR FLOW, 3D SOLUTION IN Y--Z PLANE"
compare taylor5 > taylor5.rst
les -chk taylor5 > /dev/null
compare taylor5 taylor5.fld > /dev/null
rm taylor5*

echo ""
echo "-- 3D KOVASZNAY FLOW, X--Y PLANE, DIRICHLET BCS"
les -chk kovas2 > /dev/null
compare kovas2 kovas2.fld > /dev/null
rm kovas2*

echo ""
echo "-- 3D KOVASZNAY FLOW, X--Y PLANE, SEMI-PERIODIC BOUNDARIES"
les -chk kovas3 > /dev/null
compare kovas3 kovas3.fld > /dev/null
rm kovas3*

echo ""
echo "-- 3D KOVASZNAY FLOW, X--Z PLANE, SEMI-PERIODIC BOUNDARIES"
les -chk kovas4 > /dev/null
compare kovas4 kovas4.fld > /dev/null
rm kovas4*

echo ""
echo "-- 3D KOVASZNAY FLOW, Y--Z PLANE, SEMI-PERIODIC BOUNDARIES"
les -chk kovas5 > /dev/null
compare kovas5 kovas5.fld > /dev/null
rm kovas5*


echo ""
echo ""
echo "-- CYLINDRICAL GEOMETRY --"

echo ""
echo "-- 2D POISEUILLE FLOW IN A TUBE"
compare tube1 > tube1.rst
les -chk tube1 > /dev/null
compare tube1 tube1.fld > /dev/null
rm tube1*

echo ""
echo "-- 3D POISEUILLE FLOW IN A TUBE"
compare tube2 > tube2.rst
les -chk tube2 > /dev/null
compare tube2 tube2.fld > /dev/null
rm tube2*

echo ""
echo "-- 3D UNIFORM FLOW NORMAL TO A TUBULAR VOLUME"
compare tube3 > tube3.rst
les -chk tube3 > /dev/null
compare tube3 tube3.fld > /dev/null
rm tube3*

echo ""
echo "-- 3D SOLID BODY ROTATION"
compare sbr > sbr.rst
les -chk sbr > /dev/null
compare sbr sbr.fld > /dev/null
rm sbr*

echo ""
echo "-- LOW TAYLOR NUMBER TAYLOR--COUETTE FLOW"
compare tc1 > tc1.rst
les -chk tc1 > /dev/null
compare tc1 tc1.fld > /dev/null
rm tc1*
