#!/bin/csh
# Zero Step and Time in sem.fld file.
# Warning: it seems to work reliably only if .fld file is in ASCII form.
#
# $Id$

if ($#argv < 1) then
        echo "usage: zerotime fieldfile"
        exit 0
endif

ed -s $1 << XXXfunnyXXX
4,5d
3a
0                         Step
0.0                       Time
.
w
q
XXXfunnyXXX
