#!/bin/bash

mkbase
enumerate -O3 chan3 > chan3.num
../../arnoldi -g -k 4 -n 1 -m 50 -t 1e-6 chan3 > /dev/null
cp chan3.eig.0 chan3.rst
lns chan3 > /dev/null
moden chan3.rst | integral chan3
moden chan3.fld | integral chan3



