#!/bin/csh
##############################################################################
# Run Navier--Stokes solver on test files.
# $Id$

echo "******************************************************"
echo "* Spectral element Navier--Stokes solver test suite. *"
echo "*   This is for DNS version of LES solver, must be   *"
echo "*              compiled with NOMODEL=1.              *"
echo "*                                                    *"
echo "* (NB: pressure error norms are usually irrelevant.) *"
echo "******************************************************"

set CODE=les-dyn
set MESHDIR=../semtex/mesh

if (!(-e $CODE)) then
  echo "Building application, please wait..."
  if { gmake NOMODEL=1 } then
    gmake clean
    echo "Done."
  else
    echo "Unable to compile."
    exit 1
  endif
  echo ""
endif

foreach SESS (taylor3 taylor4 taylor5 kovas2 kovas3 kovas4 kovas5)
  if (!(-e $SESS)) cp $MESHDIR/$SESS .
  if (-e $SESS.num) rm -f $SESS.num
  echo ""
  head -1 $SESS
  compare $SESS > $SESS.rst
  enumerate -O3 $SESS > $SESS.num
  $CODE -chk $SESS > /dev/null
  compare $SESS $SESS.fld > /dev/null
  rm $SESS*
end
