##############################################################################
# Makefile for finite element solver.
#
# $Id$
##############################################################################

# ----------------------------------------------------------------------------
# Installation of header files.

install:
	rm -f ../include/Sem.h ../include/Feml.h ../include/Mesh.h
	cp Sem.h Feml.h Mesh.h ../include
