##############################################################################
# Makefile for spectral element base routines.
#
# $Id$
##############################################################################

# ----------------------------------------------------------------------------
# Installation of header files.

install:
	rm -f ../include/Sem.h		\
	      ../include/Feml.h		\
	      ../include/Mesh.h		\
	      ../include/Geometry.h 
	cp Sem.h Feml.h Mesh.h Geometry.h ../include
