#ifndef PL_PTYPE_H
#define PL_PTYPE_H

/* PL
 *
 * $Id$
 *
 * Author: R. D. Henderson
 *
 * Point types recognized by PL.
 * ------------------------------------------------------------------------- */

typedef enum {
  PL_NONE,
  PL_DOT,
  PL_PLUS,
  PL_ASTERISK,
  PL_CIRCLE,
  PL_CROSS,
  PL_STAR,
  PL_SQUARE,
  PL_DIAMOND,
  PL_TRIANGLE,
  PL_INVERTED_TRIANGLE,
  PL_FILLED_SQUARE,
  PL_FILLED_DIAMOND,
  PL_FILLED_TRIANGLE,
  PL_FILLED_INVERTED_TRIANGLE,
  PL_FILLED_CIRCLE,
  PL_STARBURST,
  PL_FANCY_PLUS,
  PL_FANCY_CROSS,
  PL_FANCY_SQUARE,
  PL_FANCY_DIAMOND,
  PL_FILLED_FANCY_SQUARE,
  PL_FILLED_FANCY_DIAMOND,
  PL_HALF_FILLED_SQUARE,
  PL_HALF_FILLED_DIAMOND,
  PL_HALF_FILLED_TRIANGLE,
  PL_HALF_FILLED_INVERTED_TRIANGLE,
  PL_HALF_FILLED_CIRCLE,
  PL_HALF_FILLED_FANCY_DIAMOND,
  PL_OCTAGON,
  PL_FILLED_OCTAGON
} pl_point_t;

#endif
