#
# Sync with https://gitlab.erc.monash.edu.au/sembucket/semtex
# At noon daily or when there is a pull request on master
#

name: Sync upstream Gitlab

on:
  push:
  pull_request:
    branches:
      - master
  schedule:
  - cron:  '* 12 * * *'

jobs:
  sync_upstream:
    name: Sync Upstream with Mirror
    runs-on: ubuntu-latest
    steps:
    - id: checkout_mirror_upstream
      name: Checkout 'upstream' branch
      uses: actions/checkout@v2

    - id: sync_upstream_remote
      name: Sync 'upstream' remote
      run: |
        chmod +x .github/workflows/sync-upstream.sh
        .github/workflows/sync-upstream.sh
